spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/batch?characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  batch:
    table-prefix: BATCH_
    job:
      enabled: false
    initialize-schema: NEVER
    schema: spring_batch_ddl.sql
  quartz:
    job-store-type: JDBC
    jdbc:
      initialize-schema: NEVER
      schema: spring_quartz_ddl.sql
