spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/batch?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  batch:
    table-prefix: BATCH_
    job:
      enabled: false
    initialize-schema: NEVER
    schema: spring_batch_ddl.sql
  quartz:
    job-store-type: JDBC
    jdbc:
      initialize-schema: NEVER
      schema: spring_quartz_ddl.sql
