spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/batch?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  batch:
    table-prefix: BATCH_
    job:
      enabled: false
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
debug: true