server:
  servlet:
    context-path: /auth
  port: 9999
  address: 127.0.0.1
logging:
  level:
    org.springframework.security: DEBUG
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/auth?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: bpay-oauth2
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
security:
  oauth2:
    client:
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      user-info-uri: http://localhost:9999/auth/me