server:
  servlet:
    context-path: /auth
  port: 9999
  address: 127.0.0.1
logging:
  level:
    org.springframework.security: DEBUG
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/auth?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  application:
    name: bpay-oauth2
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true